const categories = [
  {
    id: "einhell_power_x-change_cordless_lawn_mower",
    name: "Einhell Power X-Change cordless lawn mower",
    categoryId: "lawn_mowers",
    price: 256,
    isTopPick: true,
  },
  {
    id: "hurricane_cylinder_mower_hhr_40",
    name: "Hurricane cylinder mower HHR 40",
    categoryId: "lawn_mowers",
    price: 44.9,
    isTopPick: true,
  },
  {
    id: "gardena_powermax_42_e_electric_lawn_mower",
    name: "Gardena PowerMax 42 E electric lawn mower",
    categoryId: "lawn_mowers",
    price: 219,
    isTopPick: true,
  },
  {
    id: "worx_landroid_robotic_lawnmower_m700",
    name: "Worx Landroid robotic lawnmower M700",
    categoryId: "lawn_mowers",
    price: 645,
    isTopPick: true,
  },
  {
    id: "sunfun_diana_garden_bench",
    name: "Sunfun Diana garden bench",
    categoryId: "garden_furniture",
    price: 99,
    isTopPick: true,
  },
  {
    id: "palatino_exclusive_line_firewood_rack_woodpecker",
    name: "Palatino Exclusive Line Firewood Rack Woodpecker",
    categoryId: "garden_furniture",
    price: 259,
    isTopPick: true,
  },
  {
    id: "bellissa_garden_bench_gabion_arco",
    name: "Bellissa garden bench gabion Arco",
    categoryId: "garden_furniture",
    price: 157,
    isTopPick: true,
  },
  {
    id: "sensum_garden_table_askeby",
    name: "SENSUM garden table Askeby",
    categoryId: "garden_furniture",
    price: 329,
    isTopPick: true,
  },
  {
    id: "scheppach_high-pressure_cleaner_hce2600",
    name: "Scheppach high-pressure cleaner HCE2600",
    categoryId: "",
    price: 132,
    isTopPick: true,
  },
  {
    id: "mennekes_cee_wall_socket_400v_16a",
    name: "Mennekes CEE wall socket 400V 16A",
    categoryId: "",
    price: 8.95,
    isTopPick: true,
  },
  {
    id: "eglo_townshend_ceiling_lamp",
    name: "Eglo Townshend ceiling lamp",
    categoryId: "",
    price: 53.99,
    isTopPick: true,
  },
  {
    id: "gardena_wall-mounted_hose_box_rollup",
    name: "Gardena wall-mounted hose box RollUp",
    categoryId: "",
    price: 124,
    isTopPick: true,
  },
  {
    id: "valcomp_by_mantion_sliding_door_fitting_rocline",
    name: "Valcomp by Mantion sliding door fitting Rocline",
    categoryId: "",
    price: 59.95,
    isTopPick: true,
  },
  {
    id: "einhell_cordless_vacuum_cleaner_te-vc_18_li-solo",
    name: "Einhell cordless vacuum cleaner TE-VC 18 Li-Solo",
    categoryId: "",
    price: 31.25,
    isTopPick: true,
  },
  {
    id: "camargue_kitchen_tap_flexo",
    name: "Camargue kitchen tap Flexo",
    categoryId: "",
    price: 49,
    isTopPick: true,
  },
  {
    id: "einhell_power_x-charge_battery_twinpack",
    name: "Einhell Power X-Charge battery twinpack",
    categoryId: "",
    price: 59.99,
    isTopPick: true,
  },
];

export default categories;
